events { worker_connections 2048; }

http {
    upstream api-gateway {
        server api-gateway:5000;
    }

    server {
        listen 80;

        location /orders/ {
            proxy_pass http://api-gateway;
        }

        location /payment/ {
            proxy_pass http://api-gateway;
        }

        location /stock/ {
            proxy_pass http://api-gateway;
        }

        access_log /var/log/nginx/server.access.log;
    }

    access_log /var/log/nginx/access.log;
}
