events { worker_connections 8192;}

http {
    upstream api-gateway {
        server api-gateway:5000;
    }

    server {
        listen 80;
        proxy_connect_timeout 50s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        location /orders/ {
            proxy_pass http://api-gateway;
        }

        location /payment/ {
            proxy_pass http://api-gateway;
        }

        location /stock/ {
            proxy_pass http://api-gateway;
        }

        access_log /var/log/nginx/server.access.log;
    }

    access_log /var/log/nginx/access.log;
}
