auth:
  password: redis
architecture: standalone # so these databases dont have master slave for now
master:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    enabled: true # how we keep data persisted
    size: 1Gi        # reduced from default
